### PR TITLE
migrate from JavaScript to TypeScript

### PR DESCRIPTION
**Pull request by AmrMonier**

### CODE REVIEW

**Review by warengonzaga — CHANGES_REQUESTED** [review]
Hey @AmrMonier, can you remove the `package-lock.json` file. Kindly use the `yarn` instead.

**Comment by warengonzaga** [comment]
Overall changes are good, thanks for the contribution @AmrMonier cheers!

**Comment by AmrMonier** [comment]
@warengonzaga i have updated the PR and used yarn instead of npm as you mentioned, however i have to ask i have always used npm is there any advantage of using yarn or any extra feature or it's just a matter of personal preference

**Comment by warengonzaga** [comment]
hey @AmrMonier, good question. NPM installs dependency in-sequential while yarn installs it in parallel, in that case, yarn is faster than using NPM.

**Review by warengonzaga — APPROVED** [review]
All is good to me, thank you for your contribution and help!

**Comment by AmrMonier** [comment]
@warengonzaga when would this branch get merged ?

**Comment by warengonzaga** [comment]
> 

Hey there, let me review this... I was busy these recent days. Apologies.

**Comment by warengonzaga** [comment]
Hey @AmrMonier, can you get the latest changes from `dev` branch instead of `main` branch. Your code will be outdated. Then after that, PR your changes to `dev` not in `main` branch.

I'll close this for now, kindly submit new. Thanks! 🙏

**Pull request closed without merging**
