### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by JohnDoePBabu**

### CODE REVIEW

**Comment by JohnDoePBabu** [comment]
I have added the test via Jest.
closes issue #8 
I was unsure of test title conventions for Jest. So let me know if they have to be modified.
Also, I made changes on top of the version I had implemented with mocha. Let me know if you want me to start afresh from the base.

**Comment by WarenGonzaga** [comment]
I will try this on my machine @JohnDoePBabu and let you know...

**Comment by WarenGonzaga** [comment]
@JohnDoePBabu how about this?

**Comment by JohnDoePBabu** [comment]
Let me rebase this

**Comment by WarenGonzaga** [comment]
@JohnDoePBabu do you still need this or just close this?

**Comment by JohnDoePBabu** [comment]
Will re-open after #2

**Pull request closed without merging**
